language: go

git:
  depth: 1

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.1

script:
  - golangci-lint run ./...

notifications:
  email: false